const USER='USERS'
export enum UserErrorCodes {
    
    NOT_FOUND = USER+'.NOT_FOUND',
    NOT_GREETED=USER+'.NOT_GREETED',
    MALFORMED_REQUEST=USER+'.MALFORMED_REQUEST',
    AGGREGATE_NOT_CREATED=USER+'.AGGREGATE_NOT_CREATED',
    AGGREGATE_NOT_UPDATED=USER+'.AGGREGATE_NOT_UPDATED'
  }